name: Performance

on:
  pull_request:
  push:
    branches: [main]

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ['18.x']

    name: Test on node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node }}

      - name: Install & build
        run: |
          node --version
          npm --version
          yarn --version
          yarn install --frozen-lockfile
          yarn build

      - name: Run benchmark
        run: yarn benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: benchmarkjs
          output-file-path: output.txt
          # comment for PRs that's updated with current perf relative to baseline (main)
          summary-always: true
          # warn if slowness is detected; might be transient on rerun
          alert-threshold: 110%
          comment-on-alert: true
          fail-on-alert: true
          # if things get considerably slower, deny the PR
          fail-threshold: 120%
          # needed for pushing historical results to gh-pages & commenting on PRs
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # creates a gh-pages deployment with historical benchmarking data
          auto-push: true
