name: Unit Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ['18.x']

    name: Test on node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node }}

      - name: Install deps, build, and test
        run: |
          node --version
          npm --version
          yarn --version
          yarn install --frozen-lockfile
          yarn test --coverage
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096
